name: Torbox Plex Test

services:
  app:
    build:
      context: .
      args:
        DATABASE_URL: "postgresql://torbox-plex:some-password@postgres:5432/torbox-plex"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DEBUG: 'torbox-plex:*'
    ports:
      - "3000:3000"
    networks:
      - torbox_plex
    volumes:
      - ./tmp/blackhole:/data/blackhole

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: torbox-plex
      POSTGRES_PASSWORD: some-password
      POSTGRES_DB: torbox-plex
      POSTGRES_LOGGING_LEVEL: error
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - torbox_plex
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  torbox_plex:
    driver: bridge
