name: Torbox Plex

services:
  torbox-plex:
    image: jimdrury/torbox-plex:main
    restart: unless-stopped
    networks:
      - torbox-network
    environment:
      PGID: 1000
      PUID: 1000
      DATABASE_URL: "postgresql://casaos:casaos@postgres:5432/casaos"
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./DATA/Blackhole:/data/blackhole

  postgres:
    image: postgres:15
    networks:
      - torbox-network
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/London
      POSTGRES_USER: casaos
      POSTGRES_PASSWORD: casaos
      POSTGRES_DB: casaos
      POSTGRES_LOGGING_LEVEL: error
    volumes:
      - ./DATA/AppData/postgresql/data:/var/lib/postgresql/data

networks:
  torbox-network:
    driver: bridge